plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/la-patrona/haman_porfolio/portfolio/frontend/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/la-patrona/haman_porfolio/portfolio/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]